/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package face;

import java.awt.Color;
import java.util.HashSet;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jame1850
 */
public class FaceMaker extends javax.swing.JFrame {

    /**
     * Creates new form FaceMaker
     */
    
    Face f;
    public FaceMaker() {
        initComponents();
        f = new Face(facePanel.getGraphics(), 100, 100);
        toggleMoodButton.setEnabled(false);
        changeColorButton.setEnabled(false);
        moveFaceButton.setEnabled(false);
        resizeFaceButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        moveFaceButton = new javax.swing.JButton();
        resizeFaceButton = new javax.swing.JButton();
        toggleMoodButton = new javax.swing.JButton();
        changeColorButton = new javax.swing.JButton();
        facePanel = new javax.swing.JPanel();
        setInitialFace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        moveFaceButton.setText("Move Face");
        moveFaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveFaceButtonActionPerformed(evt);
            }
        });

        resizeFaceButton.setText("Resize Face");
        resizeFaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeFaceButtonActionPerformed(evt);
            }
        });

        toggleMoodButton.setText("Toggle Mood");

        changeColorButton.setText("Change Color");
        changeColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveFaceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resizeFaceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(changeColorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleMoodButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveFaceButton)
                    .addComponent(resizeFaceButton)
                    .addComponent(toggleMoodButton)
                    .addComponent(changeColorButton))
                .addContainerGap())
        );

        facePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout facePanelLayout = new javax.swing.GroupLayout(facePanel);
        facePanel.setLayout(facePanelLayout);
        facePanelLayout.setHorizontalGroup(
            facePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        facePanelLayout.setVerticalGroup(
            facePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        setInitialFace.setText("Set Initial Face");
        setInitialFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setInitialFaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(setInitialFace, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(facePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setInitialFace)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setInitialFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setInitialFaceActionPerformed
        toggleMoodButton.setEnabled(true);
        changeColorButton.setEnabled(true);
        moveFaceButton.setEnabled(true);
        resizeFaceButton.setEnabled(true);
        f.erase();
        f = new Face(facePanel.getGraphics(), 150, 100);
        f.draw();
    }//GEN-LAST:event_setInitialFaceActionPerformed

    private void moveFaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveFaceButtonActionPerformed
        int newx, newy;
        newx = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter new position X"));
        newy = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter new position Y"));
        f.erase();
        f.move(newx, newy);
        f.draw();
    }//GEN-LAST:event_moveFaceButtonActionPerformed

    private void resizeFaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeFaceButtonActionPerformed
        int size;
        size = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter new diameter."));
        f.erase();
        f.setSize(size);
        f.draw();
    }//GEN-LAST:event_resizeFaceButtonActionPerformed

    private void changeColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeColorButtonActionPerformed
        Color eyeColor = JColorChooser.showDialog(this, "Select a new eye Color", Color.black);
        Color faceColor = JColorChooser.showDialog(this, "Pick a new face Color", Color.white);
        f.erase();
        f.setColor(eyeColor, faceColor);
        f.draw();
    }//GEN-LAST:event_changeColorButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaceMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaceMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaceMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaceMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaceMaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeColorButton;
    private javax.swing.JPanel facePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton moveFaceButton;
    private javax.swing.JButton resizeFaceButton;
    private javax.swing.JButton setInitialFace;
    private javax.swing.JButton toggleMoodButton;
    // End of variables declaration//GEN-END:variables
}
